### PR TITLE
Add tox, travis, fix static check errors

### PR DESCRIPTION
**Pull request by gdyuldin**

### CODE REVIEW

**Comment by schipiga** [comment]
@gdyuldin, please, move your pull-request to [gerrithub](https://review.gerrithub.io/#/admin/projects/Mirantis/stepler)

**Comment by gdyuldin** [comment]
Now gerrit repo is outsynced, so i can't upload this commit to it. 
https://review.gerrithub.io/static/intro.html (How can I resume replication to GitHub ? section)

**Comment by TimurNurlygayanov** [comment]
https://review.gerrithub.io/#/c/296371/

**Comment by TimurNurlygayanov** [comment]
it is synced with gerrithub already. please do not merge this poll request in github.

**Pull request closed without merging**
